apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: paycrypt
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws
  namespace: paycrypt
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: paycrypt
spec:
  replicas: 1
